// <auto-generated />
using System;
using BBB_ApplicationDashboard.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BBB_ApplicationDashboard.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250924221311_ChangeRevenueToLong")]
    partial class ChangeRevenueToLong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BBB_ApplicationDashboard.Domain.Entities.Accreditation", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalBusinessInformation")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ApplicationStatusExternal")
                        .HasColumnType("integer");

                    b.Property<int>("ApplicationStatusInternal")
                        .HasColumnType("integer");

                    b.Property<string>("AvgCustomersPerYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BID")
                        .HasColumnType("text");

                    b.Property<string>("BlueApplicationID")
                        .HasColumnType("text");

                    b.Property<string>("BusinessAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessAptSuite")
                        .HasColumnType("text");

                    b.Property<string>("BusinessCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessEntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessServiceArea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("BusinessStartDate")
                        .HasColumnType("date");

                    b.Property<string>("BusinessState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessZip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyRecordID")
                        .HasColumnType("text");

                    b.Property<string>("DoingBusinessAs")
                        .HasColumnType("text");

                    b.Property<string>("EIN")
                        .HasColumnType("text");

                    b.Property<string>("EmailToReceiveQuoteRequestsFromCustomers")
                        .HasColumnType("text");

                    b.Property<long>("GrossAnnualRevenue")
                        .HasColumnType("bigint");

                    b.Property<string>("HubSpotApplicationID")
                        .HasColumnType("text");

                    b.Property<string>("Licenses")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("MailingAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MailingCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MailingState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MailingZip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfFullTimeEmployees")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfLocations")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfPartTimeEmployees")
                        .HasColumnType("integer");

                    b.Property<int>("PartnershipSource")
                        .HasColumnType("integer");

                    b.Property<string>("PreferredContactMethod")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryBusinessEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryBusinessPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryContactTypes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateOnly>("PrimaryDateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("PrimaryFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondaryContactTypes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SecondaryEmail")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryFirstName")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryLastName")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryPhone")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryPreferredContactMethod")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryTitle")
                        .HasColumnType("text");

                    b.Property<string>("SocialMediaLinks")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SubmittedByEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubmittedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubmittedByTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrackingLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("ApplicationId");

                    b.ToTable("Accreditations");
                });

            modelBuilder.Entity("BBB_ApplicationDashboard.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserSource")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
