name: Build and Deploy to Coolify

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE: omar0saleh/application-dashboard

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64

      - name: Trigger Coolify Deployment
        if: github.ref == 'refs/heads/main'
        uses: gitnasr/coolify-trigger-deploy@v2.0.0
        with:
          docker_image: ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
          coolify_url: ${{ secrets.COOLIFY_URL }}
          coolify_resource_id: ${{ secrets.COOLIFY_RESOURCE_ID }}
          coolify_api_token: ${{ secrets.COOLIFY_API_TOKEN }}
